# ci-cd setup
---
- name:  jenkin server setup
  hosts: jenkinserver
  tasks:
    - name: install sw's
      apt:
        name: "{{item.a}}"
        state: "{{item.b}}"
        update_cache: "{{item.c}}"
      with_items:
        - {a: openjdk-8-jdk,b: present,c: yes}
        - {a: git,b: present,c: no}
        - {a: maven,b: present,c: no}
    - name: download jenkins.war file
      get_url:
        url:
        dest: /home/ubuntu
- name: qa and prod server setup
  hosts: servers
  tasks:
    - name: install tomcat9 and tomcat9-admin
      apt:
        name: ["tomcat9","tomcat9-admin"]
        state: present
        update_cache: yes
      copy: copy tomcat-users.xml file
        src: tomcat-users.xml
        dest: /etc/tomcat9/
      notify: restart tomcat9           
  handlers:
    - name: restart tomcat9    
      service:
        name: tomcat9
        state: restarted
- name: check url response
  hosts: servers
  tasks:
    - uri:
        url: "{{item}}"
      with_items:
        - http://172.31.28.4:9090
        - http://172.31.29.43:9090          
...        

