---
- name: configure tomcat9
  hosts: all
  tasks:
    - name: install tomcat9
      apt:
        name: tomcat9
        state: present
        update_cache: yes
    - name: install tomcat9-admin
      apt:
        name: tomcat9-admin
        state: present
    - name: edit tomcat-users.xml file
      copy:
        src: tomcat-users.xml
        dest: /etc/tomcat9/
    - name: change the default port number
      replace:
        regexp: 8080
        replace: 9090
        path: /etc/tomcat9/server.xml
    - name: restart tomcat9
      service:
        name: tomcat9
        state: restarted
    - name: pause for 3mins
      pause:
        minutes: 3
    - name: url check on server1
      uri:
        url: http://172.31.29.43:9090
        status_code: 200
    - name: url check on server2
      uri:
        url: http://172.31.28.4:9090
        status_code: 200
...                                    
command: ansible-playbook playbook2.yml -b